int BOTAO = 7; //PINO DIGITAL UTILIZADO PELO PUSH BUTTON
int LED = 13; //PINO DIGITAL UTILIZADO PELO LED

void setup() {
  pinMode(BOTAO, INPUT_PULLUP); //DEFINE O PINO COMO ENTRADA / "_PULLUP" É PARA ATIVAR O RESISTOR INTERNO
  //DO ARDUINO PARA GARANTIR QUE NÃO EXISTA FLUTUAÇÃO ENTRE 0 (LOW) E 1 (HIGH)
  pinMode(LED, OUTPUT); //DEFINE O PINO COMO SAÍDA

  digitalWrite(LED, LOW); //LED INICIA DESLIGADO
}
void loop(){
  if(digitalRead(BOTAO) == LOW){ //SE A LEITURA DO PINO FOR IGUAL A LOW, FAZ
    digitalWrite(LED, HIGH); //ACENDE O LED
    delay(4000);
  }
  else{ //SENÃO, FAZ
    digitalWrite(LED, LOW); //APAGA O LED

  }
}

